<?php

if ( ! class_exists( 'CTF_Help' ) ) :

class CTF_Help
{
	
	public static $is_fields_printed_at_admin_footer = false;
	
	function __construct()
	{
	}

	public static function get_google_font_json() {
		$json = '{"ABeeZee":["400"],"Abel":["400"],"Abril Fatface":["400"],"Aclonica":["400"],"Acme":["400"],"Actor":["400"],"Adamina":["400"],"Advent Pro":["100","200","300","400","500","600","700"],"Aguafina Script":["400"],"Akronim":["400"],"Aladin":["400"],"Aldrich":["400"],"Alef":["400","700"],"Alegreya":["400","700","900"],"Alegreya SC":["400","700","900"],"Alegreya Sans":["100","300","400","500","700","800","900"],"Alegreya Sans SC":["100","300","400","500","700","800","900"],"Alex Brush":["400"],"Alfa Slab One":["400"],"Alice":["400"],"Alike":["400"],"Alike Angular":["400"],"Allan":["400","700"],"Allerta":["400"],"Allerta Stencil":["400"],"Allura":["400"],"Almendra":["400","700"],"Almendra Display":["400"],"Almendra SC":["400"],"Amarante":["400"],"Amaranth":["400","700"],"Amatic SC":["400","700"],"Amethysta":["400"],"Amiri":["400","700"],"Amita":["400","700"],"Anaheim":["400"],"Andada":["400"],"Andika":["400"],"Angkor":["400"],"Annie Use Your Telescope":["400"],"Anonymous Pro":["400","700"],"Antic":["400"],"Antic Didone":["400"],"Antic Slab":["400"],"Anton":["400"],"Arapey":["400"],"Arbutus":["400"],"Arbutus Slab":["400"],"Architects Daughter":["400"],"Archivo Black":["400"],"Archivo Narrow":["400","700"],"Arimo":["400","700"],"Arizonia":["400"],"Armata":["400"],"Artifika":["400"],"Arvo":["400","700"],"Arya":["400","700"],"Asap":["400","700"],"Asar":["400"],"Asset":["400"],"Astloch":["400","700"],"Asul":["400","700"],"Atomic Age":["400"],"Aubrey":["400"],"Audiowide":["400"],"Autour One":["400"],"Average":["400"],"Average Sans":["400"],"Averia Gruesa Libre":["400"],"Averia Libre":["300","400","700"],"Averia Sans Libre":["300","400","700"],"Averia Serif Libre":["300","400","700"],"Bad Script":["400"],"Balthazar":["400"],"Bangers":["400"],"Basic":["400"],"Battambang":["400","700"],"Baumans":["400"],"Bayon":["400"],"Belgrano":["400"],"Belleza":["400"],"BenchNine":["300","400","700"],"Bentham":["400"],"Berkshire Swash":["400"],"Bevan":["400"],"Bigelow Rules":["400"],"Bigshot One":["400"],"Bilbo":["400"],"Bilbo Swash Caps":["400"],"Biryani":["200","300","400","600","700","800","900"],"Bitter":["400","700"],"Black Ops One":["400"],"Bokor":["400"],"Bonbon":["400"],"Boogaloo":["400"],"Bowlby One":["400"],"Bowlby One SC":["400"],"Brawler":["400"],"Bree Serif":["400"],"Bubblegum Sans":["400"],"Bubbler One":["400"],"Buda":["300"],"Buenard":["400","700"],"Butcherman":["400"],"Butterfly Kids":["400"],"Cabin":["400","500","600","700"],"Cabin Condensed":["400","500","600","700"],"Cabin Sketch":["400","700"],"Caesar Dressing":["400"],"Cagliostro":["400"],"Calligraffitti":["400"],"Cambay":["400","700"],"Cambo":["400"],"Candal":["400"],"Cantarell":["400","700"],"Cantata One":["400"],"Cantora One":["400"],"Capriola":["400"],"Cardo":["400","700"],"Carme":["400"],"Carrois Gothic":["400"],"Carrois Gothic SC":["400"],"Carter One":["400"],"Catamaran":["100","200","300","400","500","600","700","800","900"],"Caudex":["400","700"],"Cedarville Cursive":["400"],"Ceviche One":["400"],"Changa One":["400"],"Chango":["400"],"Chau Philomene One":["400"],"Chela One":["400"],"Chelsea Market":["400"],"Chenla":["400"],"Cherry Cream Soda":["400"],"Cherry Swash":["400","700"],"Chewy":["400"],"Chicle":["400"],"Chivo":["400","900"],"Chonburi":["400"],"Cinzel":["400","700","900"],"Cinzel Decorative":["400","700","900"],"Clicker Script":["400"],"Coda":["400","800"],"Coda Caption":["800"],"Codystar":["300","400"],"Combo":["400"],"Comfortaa":["300","400","700"],"Coming Soon":["400"],"Concert One":["400"],"Condiment":["400"],"Content":["400","700"],"Contrail One":["400"],"Convergence":["400"],"Cookie":["400"],"Copse":["400"],"Corben":["400","700"],"Courgette":["400"],"Cousine":["400","700"],"Coustard":["400","900"],"Covered By Your Grace":["400"],"Crafty Girls":["400"],"Creepster":["400"],"Crete Round":["400"],"Crimson Text":["400","600","700"],"Croissant One":["400"],"Crushed":["400"],"Cuprum":["400","700"],"Cutive":["400"],"Cutive Mono":["400"],"Damion":["400"],"Dancing Script":["400","700"],"Dangrek":["400"],"Dawning of a New Day":["400"],"Days One":["400"],"Dekko":["400"],"Delius":["400"],"Delius Swash Caps":["400"],"Delius Unicase":["400","700"],"Della Respira":["400"],"Denk One":["400"],"Devonshire":["400"],"Dhurjati":["400"],"Didact Gothic":["400"],"Diplomata":["400"],"Diplomata SC":["400"],"Domine":["400","700"],"Donegal One":["400"],"Doppio One":["400"],"Dorsa":["400"],"Dosis":["200","300","400","500","600","700","800"],"Dr Sugiyama":["400"],"Droid Sans":["400","700"],"Droid Sans Mono":["400"],"Droid Serif":["400","700"],"Duru Sans":["400"],"Dynalight":["400"],"EB Garamond":["400"],"Eagle Lake":["400"],"Eater":["400"],"Economica":["400","700"],"Eczar":["400","500","600","700","800"],"Ek Mukta":["200","300","400","500","600","700","800"],"Electrolize":["400"],"Elsie":["400","900"],"Elsie Swash Caps":["400","900"],"Emblema One":["400"],"Emilys Candy":["400"],"Engagement":["400"],"Englebert":["400"],"Enriqueta":["400","700"],"Erica One":["400"],"Esteban":["400"],"Euphoria Script":["400"],"Ewert":["400"],"Exo":["100","200","300","400","500","600","700","800","900"],"Exo 2":["100","200","300","400","500","600","700","800","900"],"Expletus Sans":["400","500","600","700"],"Fanwood Text":["400"],"Fascinate":["400"],"Fascinate Inline":["400"],"Faster One":["400"],"Fasthand":["400"],"Fauna One":["400"],"Federant":["400"],"Federo":["400"],"Felipa":["400"],"Fenix":["400"],"Finger Paint":["400"],"Fira Mono":["400","700"],"Fira Sans":["300","400","500","700"],"Fjalla One":["400"],"Fjord One":["400"],"Flamenco":["300","400"],"Flavors":["400"],"Fondamento":["400"],"Fontdiner Swanky":["400"],"Forum":["400"],"Francois One":["400"],"Freckle Face":["400"],"Fredericka the Great":["400"],"Fredoka One":["400"],"Freehand":["400"],"Fresca":["400"],"Frijole":["400"],"Fruktur":["400"],"Fugaz One":["400"],"GFS Didot":["400"],"GFS Neohellenic":["400","700"],"Gabriela":["400"],"Gafata":["400"],"Galdeano":["400"],"Galindo":["400"],"Gentium Basic":["400","700"],"Gentium Book Basic":["400","700"],"Geo":["400"],"Geostar":["400"],"Geostar Fill":["400"],"Germania One":["400"],"Gidugu":["400"],"Gilda Display":["400"],"Give You Glory":["400"],"Glass Antiqua":["400"],"Glegoo":["400","700"],"Gloria Hallelujah":["400"],"Goblin One":["400"],"Gochi Hand":["400"],"Gorditas":["400","700"],"Goudy Bookletter 1911":["400"],"Graduate":["400"],"Grand Hotel":["400"],"Gravitas One":["400"],"Great Vibes":["400"],"Griffy":["400"],"Gruppo":["400"],"Gudea":["400","700"],"Gurajada":["400"],"Habibi":["400"],"Halant":["300","400","500","600","700"],"Hammersmith One":["400"],"Hanalei":["400"],"Hanalei Fill":["400"],"Handlee":["400"],"Hanuman":["400","700"],"Happy Monkey":["400"],"Headland One":["400"],"Henny Penny":["400"],"Herr Von Muellerhoff":["400"],"Hind":["300","400","500","600","700"],"Holtwood One SC":["400"],"Homemade Apple":["400"],"Homenaje":["400"],"IM Fell DW Pica":["400"],"IM Fell DW Pica SC":["400"],"IM Fell Double Pica":["400"],"IM Fell Double Pica SC":["400"],"IM Fell English":["400"],"IM Fell English SC":["400"],"IM Fell French Canon":["400"],"IM Fell French Canon SC":["400"],"IM Fell Great Primer":["400"],"IM Fell Great Primer SC":["400"],"Iceberg":["400"],"Iceland":["400"],"Imprima":["400"],"Inconsolata":["400","700"],"Inder":["400"],"Indie Flower":["400"],"Inika":["400","700"],"Inknut Antiqua":["300","400","500","600","700","800","900"],"Irish Grover":["400"],"Istok Web":["400","700"],"Italiana":["400"],"Italianno":["400"],"Itim":["400"],"Jacques Francois":["400"],"Jacques Francois Shadow":["400"],"Jaldi":["400","700"],"Jim Nightshade":["400"],"Jockey One":["400"],"Jolly Lodger":["400"],"Josefin Sans":["100","300","400","600","700"],"Josefin Slab":["100","300","400","600","700"],"Joti One":["400"],"Judson":["400","700"],"Julee":["400"],"Julius Sans One":["400"],"Junge":["400"],"Jura":["300","400","500","600"],"Just Another Hand":["400"],"Just Me Again Down Here":["400"],"Kadwa":["400","700"],"Kalam":["300","400","700"],"Kameron":["400","700"],"Kantumruy":["300","400","700"],"Karla":["400","700"],"Karma":["300","400","500","600","700"],"Kaushan Script":["400"],"Kavoon":["400"],"Kdam Thmor":["400"],"Keania One":["400"],"Kelly Slab":["400"],"Kenia":["400"],"Khand":["300","400","500","600","700"],"Khmer":["400"],"Khula":["300","400","600","700","800"],"Kite One":["400"],"Knewave":["400"],"Kotta One":["400"],"Koulen":["400"],"Kranky":["400"],"Kreon":["300","400","700"],"Kristi":["400"],"Krona One":["400"],"Kurale":["400"],"La Belle Aurore":["400"],"Laila":["300","400","500","600","700"],"Lakki Reddy":["400"],"Lancelot":["400"],"Lateef":["400"],"Lato":["100","300","400","700","900"],"League Script":["400"],"Leckerli One":["400"],"Ledger":["400"],"Lekton":["400","700"],"Lemon":["400"],"Libre Baskerville":["400","700"],"Life Savers":["400","700"],"Lilita One":["400"],"Lily Script One":["400"],"Limelight":["400"],"Linden Hill":["400"],"Lobster":["400"],"Lobster Two":["400","700"],"Londrina Outline":["400"],"Londrina Shadow":["400"],"Londrina Sketch":["400"],"Londrina Solid":["400"],"Lora":["400","700"],"Love Ya Like A Sister":["400"],"Loved by the King":["400"],"Lovers Quarrel":["400"],"Luckiest Guy":["400"],"Lusitana":["400","700"],"Lustria":["400"],"Macondo":["400"],"Macondo Swash Caps":["400"],"Magra":["400","700"],"Maiden Orange":["400"],"Mako":["400"],"Mallanna":["400"],"Mandali":["400"],"Marcellus":["400"],"Marcellus SC":["400"],"Marck Script":["400"],"Margarine":["400"],"Marko One":["400"],"Marmelad":["400"],"Martel":["200","300","400","600","700","800","900"],"Martel Sans":["200","300","400","600","700","800","900"],"Marvel":["400","700"],"Mate":["400"],"Mate SC":["400"],"Maven Pro":["400","500","700","900"],"McLaren":["400"],"Meddon":["400"],"MedievalSharp":["400"],"Medula One":["400"],"Megrim":["400"],"Meie Script":["400"],"Merienda":["400","700"],"Merienda One":["400"],"Merriweather":["300","400","700","900"],"Merriweather Sans":["300","400","700","800"],"Metal":["400"],"Metal Mania":["400"],"Metamorphous":["400"],"Metrophobic":["400"],"Michroma":["400"],"Milonga":["400"],"Miltonian":["400"],"Miltonian Tattoo":["400"],"Miniver":["400"],"Miss Fajardose":["400"],"Modak":["400"],"Modern Antiqua":["400"],"Molengo":["400"],"Monda":["400","700"],"Monofett":["400"],"Monoton":["400"],"Monsieur La Doulaise":["400"],"Montaga":["400"],"Montez":["400"],"Montserrat":["400","700"],"Montserrat Alternates":["400","700"],"Montserrat Subrayada":["400","700"],"Moul":["400"],"Moulpali":["400"],"Mountains of Christmas":["400","700"],"Mouse Memoirs":["400"],"Mr Bedfort":["400"],"Mr Dafoe":["400"],"Mr De Haviland":["400"],"Mrs Saint Delafield":["400"],"Mrs Sheppards":["400"],"Muli":["300","400"],"Mystery Quest":["400"],"NTR":["400"],"Neucha":["400"],"Neuton":["200","300","400","700","800"],"New Rocker":["400"],"News Cycle":["400","700"],"Niconne":["400"],"Nixie One":["400"],"Nobile":["400","700"],"Nokora":["400","700"],"Norican":["400"],"Nosifer":["400"],"Nothing You Could Do":["400"],"Noticia Text":["400","700"],"Noto Sans":["400","700"],"Noto Serif":["400","700"],"Nova Cut":["400"],"Nova Flat":["400"],"Nova Mono":["400"],"Nova Oval":["400"],"Nova Round":["400"],"Nova Script":["400"],"Nova Slim":["400"],"Nova Square":["400"],"Numans":["400"],"Nunito":["300","400","700"],"Odor Mean Chey":["400"],"Offside":["400"],"Old Standard TT":["400","700"],"Oldenburg":["400"],"Oleo Script":["400","700"],"Oleo Script Swash Caps":["400","700"],"Open Sans":["300","400","600","700","800"],"Open Sans Condensed":["300","700"],"Oranienbaum":["400"],"Orbitron":["400","500","700","900"],"Oregano":["400"],"Orienta":["400"],"Original Surfer":["400"],"Oswald":["300","400","700"],"Over the Rainbow":["400"],"Overlock":["400","700","900"],"Overlock SC":["400"],"Ovo":["400"],"Oxygen":["300","400","700"],"Oxygen Mono":["400"],"PT Mono":["400"],"PT Sans":["400","700"],"PT Sans Caption":["400","700"],"PT Sans Narrow":["400","700"],"PT Serif":["400","700"],"PT Serif Caption":["400"],"Pacifico":["400"],"Palanquin":["100","200","300","400","500","600","700"],"Palanquin Dark":["400","500","600","700"],"Paprika":["400"],"Parisienne":["400"],"Passero One":["400"],"Passion One":["400","700","900"],"Pathway Gothic One":["400"],"Patrick Hand":["400"],"Patrick Hand SC":["400"],"Patua One":["400"],"Paytone One":["400"],"Peddana":["400"],"Peralta":["400"],"Permanent Marker":["400"],"Petit Formal Script":["400"],"Petrona":["400"],"Philosopher":["400","700"],"Piedra":["400"],"Pinyon Script":["400"],"Pirata One":["400"],"Plaster":["400"],"Play":["400","700"],"Playball":["400"],"Playfair Display":["400","700","900"],"Playfair Display SC":["400","700","900"],"Podkova":["400","700"],"Poiret One":["400"],"Poller One":["400"],"Poly":["400"],"Pompiere":["400"],"Pontano Sans":["400"],"Poppins":["300","400","500","600","700"],"Port Lligat Sans":["400"],"Port Lligat Slab":["400"],"Pragati Narrow":["400","700"],"Prata":["400"],"Preahvihear":["400"],"Press Start 2P":["400"],"Princess Sofia":["400"],"Prociono":["400"],"Prosto One":["400"],"Puritan":["400","700"],"Purple Purse":["400"],"Quando":["400"],"Quantico":["400","700"],"Quattrocento":["400","700"],"Quattrocento Sans":["400","700"],"Questrial":["400"],"Quicksand":["300","400","700"],"Quintessential":["400"],"Qwigley":["400"],"Racing Sans One":["400"],"Radley":["400"],"Rajdhani":["300","400","500","600","700"],"Raleway":["100","200","300","400","500","600","700","800","900"],"Raleway Dots":["400"],"Ramabhadra":["400"],"Ramaraja":["400"],"Rambla":["400","700"],"Rammetto One":["400"],"Ranchers":["400"],"Rancho":["400"],"Ranga":["400","700"],"Rationale":["400"],"Ravi Prakash":["400"],"Redressed":["400"],"Reenie Beanie":["400"],"Revalia":["400"],"Rhodium Libre":["400"],"Ribeye":["400"],"Ribeye Marrow":["400"],"Righteous":["400"],"Risque":["400"],"Roboto":["100","300","400","500","700","900"],"Roboto Condensed":["300","400","700"],"Roboto Mono":["100","300","400","500","700"],"Roboto Slab":["100","300","400","700"],"Rochester":["400"],"Rock Salt":["400"],"Rokkitt":["400","700"],"Romanesco":["400"],"Ropa Sans":["400"],"Rosario":["400","700"],"Rosarivo":["400"],"Rouge Script":["400"],"Rozha One":["400"],"Rubik":["300","400","500","700","900"],"Rubik Mono One":["400"],"Rubik One":["400"],"Ruda":["400","700","900"],"Rufina":["400","700"],"Ruge Boogie":["400"],"Ruluko":["400"],"Rum Raisin":["400"],"Ruslan Display":["400"],"Russo One":["400"],"Ruthie":["400"],"Rye":["400"],"Sacramento":["400"],"Sahitya":["400","700"],"Sail":["400"],"Salsa":["400"],"Sanchez":["400"],"Sancreek":["400"],"Sansita One":["400"],"Sarala":["400","700"],"Sarina":["400"],"Sarpanch":["400","500","600","700","800","900"],"Satisfy":["400"],"Scada":["400","700"],"Scheherazade":["400"],"Schoolbell":["400"],"Seaweed Script":["400"],"Sevillana":["400"],"Seymour One":["400"],"Shadows Into Light":["400"],"Shadows Into Light Two":["400"],"Shanti":["400"],"Share":["400","700"],"Share Tech":["400"],"Share Tech Mono":["400"],"Shojumaru":["400"],"Short Stack":["400"],"Siemreap":["400"],"Sigmar One":["400"],"Signika":["300","400","600","700"],"Signika Negative":["300","400","600","700"],"Simonetta":["400","900"],"Sintony":["400","700"],"Sirin Stencil":["400"],"Six Caps":["400"],"Skranji":["400","700"],"Slabo 13px":["400"],"Slabo 27px":["400"],"Slackey":["400"],"Smokum":["400"],"Smythe":["400"],"Sniglet":["400","800"],"Snippet":["400"],"Snowburst One":["400"],"Sofadi One":["400"],"Sofia":["400"],"Sonsie One":["400"],"Sorts Mill Goudy":["400"],"Source Code Pro":["200","300","400","500","600","700","900"],"Source Sans Pro":["200","300","400","600","700","900"],"Source Serif Pro":["400","600","700"],"Special Elite":["400"],"Spicy Rice":["400"],"Spinnaker":["400"],"Spirax":["400"],"Squada One":["400"],"Sree Krushnadevaraya":["400"],"Stalemate":["400"],"Stalinist One":["400"],"Stardos Stencil":["400","700"],"Stint Ultra Condensed":["400"],"Stint Ultra Expanded":["400"],"Stoke":["300","400"],"Strait":["400"],"Sue Ellen Francisco":["400"],"Sumana":["400","700"],"Sunshiney":["400"],"Supermercado One":["400"],"Sura":["400","700"],"Suranna":["400"],"Suravaram":["400"],"Suwannaphum":["400"],"Swanky and Moo Moo":["400"],"Syncopate":["400","700"],"Tangerine":["400","700"],"Taprom":["400"],"Tauri":["400"],"Teko":["300","400","500","600","700"],"Telex":["400"],"Tenali Ramakrishna":["400"],"Tenor Sans":["400"],"Text Me One":["400"],"The Girl Next Door":["400"],"Tienne":["400","700","900"],"Tillana":["400","500","600","700","800"],"Timmana":["400"],"Tinos":["400","700"],"Titan One":["400"],"Titillium Web":["200","300","400","600","700","900"],"Trade Winds":["400"],"Trocchi":["400"],"Trochut":["400","700"],"Trykker":["400"],"Tulpen One":["400"],"Ubuntu":["300","400","500","700"],"Ubuntu Condensed":["400"],"Ubuntu Mono":["400","700"],"Ultra":["400"],"Uncial Antiqua":["400"],"Underdog":["400"],"Unica One":["400"],"UnifrakturCook":["700"],"UnifrakturMaguntia":["400"],"Unkempt":["400","700"],"Unlock":["400"],"Unna":["400"],"VT323":["400"],"Vampiro One":["400"],"Varela":["400"],"Varela Round":["400"],"Vast Shadow":["400"],"Vesper Libre":["400","500","700","900"],"Vibur":["400"],"Vidaloka":["400"],"Viga":["400"],"Voces":["400"],"Volkhov":["400","700"],"Vollkorn":["400","700"],"Voltaire":["400"],"Waiting for the Sunrise":["400"],"Wallpoet":["400"],"Walter Turncoat":["400"],"Warnes":["400"],"Wellfleet":["400"],"Wendy One":["400"],"Wire One":["400"],"Work Sans":["100","200","300","400","500","600","700","800","900"],"Yanone Kaffeesatz":["200","300","400","700"],"Yantramanav":["100","300","400","500","700","900"],"Yellowtail":["400"],"Yeseva One":["400"],"Yesteryear":["400"],"Zeyada":["400"]}';

		return $json;
	}
	
	public static function get_icons_json(){
		return json_encode(self::get_icons_array());
	}
	
	public static function get_icons_array(){
		$icon_font =  array(
			"fa fa-glass" => "Glass",
			"fa fa-music" => "Music",
			"fa fa-search" => "Search",
			"fa fa-envelope-o" => "Envelope Outlined",
			"fa fa-heart" => "Heart",
			"fa fa-star" => "Star",
			"fa fa-star-o" => "Star Outlined",
			"fa fa-user" => "User",
			"fa fa-film" => "Film",
			"fa fa-th-large" => "th-large",
			"fa fa-th" => "th",
			"fa fa-th-list" => "th-list",
			"fa fa-check" => "Check",
			"fa fa-times" => "Times",
			"fa fa-search-plus" => "Search Plus",
			"fa fa-search-minus" => "Search Minus",
			"fa fa-power-off" => "Power Off",
			"fa fa-signal" => "signal",
			"fa fa-cog" => "cog",
			"fa fa-trash-o" => "Trash Outlined",
			"fa fa-home" => "home",
			"fa fa-file-o" => "File Outlined",
			"fa fa-clock-o" => "Clock Outlined",
			"fa fa-road" => "road",
			"fa fa-download" => "Download",
			"fa fa-arrow-circle-o-down" => "Arrow Circle Outlined Down",
			"fa fa-arrow-circle-o-up" => "Arrow Circle Outlined Up",
			"fa fa-inbox" => "inbox",
			"fa fa-play-circle-o" => "Play Circle Outlined",
			"fa fa-repeat" => "Repeat",
			"fa fa-refresh" => "refresh",
			"fa fa-list-alt" => "list-alt",
			"fa fa-lock" => "lock",
			"fa fa-flag" => "flag",
			"fa fa-headphones" => "headphones",
			"fa fa-volume-off" => "volume-off",
			"fa fa-volume-down" => "volume-down",
			"fa fa-volume-up" => "volume-up",
			"fa fa-qrcode" => "qrcode",
			"fa fa-barcode" => "barcode",
			"fa fa-tag" => "tag",
			"fa fa-tags" => "tags",
			"fa fa-book" => "book",
			"fa fa-bookmark" => "bookmark",
			"fa fa-print" => "print",
			"fa fa-camera" => "camera",
			"fa fa-font" => "font",
			"fa fa-bold" => "bold",
			"fa fa-italic" => "italic",
			"fa fa-text-height" => "text-height",
			"fa fa-text-width" => "text-width",
			"fa fa-align-left" => "align-left",
			"fa fa-align-center" => "align-center",
			"fa fa-align-right" => "align-right",
			"fa fa-align-justify" => "align-justify",
			"fa fa-list" => "list",
			"fa fa-outdent" => "Outdent",
			"fa fa-indent" => "Indent",
			"fa fa-video-camera" => "Video Camera",
			"fa fa-picture-o" => "Picture Outlined",
			"fa fa-pencil" => "pencil",
			"fa fa-map-marker" => "map-marker",
			"fa fa-adjust" => "adjust",
			"fa fa-tint" => "tint",
			"fa fa-pencil-square-o" => "Pencil Square Outlined",
			"fa fa-share-square-o" => "Share Square Outlined",
			"fa fa-check-square-o" => "Check Square Outlined",
			"fa fa-arrows" => "Arrows",
			"fa fa-step-backward" => "step-backward",
			"fa fa-fast-backward" => "fast-backward",
			"fa fa-backward" => "backward",
			"fa fa-play" => "play",
			"fa fa-pause" => "pause",
			"fa fa-stop" => "stop",
			"fa fa-forward" => "forward",
			"fa fa-fast-forward" => "fast-forward",
			"fa fa-step-forward" => "step-forward",
			"fa fa-eject" => "eject",
			"fa fa-chevron-left" => "chevron-left",
			"fa fa-chevron-right" => "chevron-right",
			"fa fa-plus-circle" => "Plus Circle",
			"fa fa-minus-circle" => "Minus Circle",
			"fa fa-times-circle" => "Times Circle",
			"fa fa-check-circle" => "Check Circle",
			"fa fa-question-circle" => "Question Circle",
			"fa fa-info-circle" => "Info Circle",
			"fa fa-crosshairs" => "Crosshairs",
			"fa fa-times-circle-o" => "Times Circle Outlined",
			"fa fa-check-circle-o" => "Check Circle Outlined",
			"fa fa-ban" => "ban",
			"fa fa-arrow-left" => "arrow-left",
			"fa fa-arrow-right" => "arrow-right",
			"fa fa-arrow-up" => "arrow-up",
			"fa fa-arrow-down" => "arrow-down",
			"fa fa-share" => "Share",
			"fa fa-expand" => "Expand",
			"fa fa-compress" => "Compress",
			"fa fa-plus" => "plus",
			"fa fa-minus" => "minus",
			"fa fa-asterisk" => "asterisk",
			"fa fa-exclamation-circle" => "Exclamation Circle",
			"fa fa-gift" => "gift",
			"fa fa-leaf" => "leaf",
			"fa fa-fire" => "fire",
			"fa fa-eye" => "Eye",
			"fa fa-eye-slash" => "Eye Slash",
			"fa fa-exclamation-triangle" => "Exclamation Triangle",
			"fa fa-plane" => "plane",
			"fa fa-calendar" => "calendar",
			"fa fa-random" => "random",
			"fa fa-comment" => "comment",
			"fa fa-magnet" => "magnet",
			"fa fa-chevron-up" => "chevron-up",
			"fa fa-chevron-down" => "chevron-down",
			"fa fa-retweet" => "retweet",
			"fa fa-shopping-cart" => "shopping-cart",
			"fa fa-folder" => "Folder",
			"fa fa-folder-open" => "Folder Open",
			"fa fa-arrows-v" => "Arrows Vertical",
			"fa fa-arrows-h" => "Arrows Horizontal",
			"fa fa-bar-chart" => "Bar Chart",
			"fa fa-twitter-square" => "Twitter Square",
			"fa fa-facebook-square" => "Facebook Square",
			"fa fa-camera-retro" => "camera-retro",
			"fa fa-key" => "key",
			"fa fa-cogs" => "cogs",
			"fa fa-comments" => "comments",
			"fa fa-thumbs-o-up" => "Thumbs Up Outlined",
			"fa fa-thumbs-o-down" => "Thumbs Down Outlined",
			"fa fa-star-half" => "star-half",
			"fa fa-heart-o" => "Heart Outlined",
			"fa fa-sign-out" => "Sign Out",
			"fa fa-linkedin-square" => "LinkedIn Square",
			"fa fa-thumb-tack" => "Thumb Tack",
			"fa fa-external-link" => "External Link",
			"fa fa-sign-in" => "Sign In",
			"fa fa-trophy" => "trophy",
			"fa fa-github-square" => "GitHub Square",
			"fa fa-upload" => "Upload",
			"fa fa-lemon-o" => "Lemon Outlined",
			"fa fa-phone" => "Phone",
			"fa fa-square-o" => "Square Outlined",
			"fa fa-bookmark-o" => "Bookmark Outlined",
			"fa fa-phone-square" => "Phone Square",
			"fa fa-twitter" => "Twitter",
			"fa fa-facebook" => "Facebook",
			"fa fa-github" => "GitHub",
			"fa fa-unlock" => "unlock",
			"fa fa-credit-card" => "credit-card",
			"fa fa-rss" => "rss",
			"fa fa-hdd-o" => "HDD",
			"fa fa-bullhorn" => "bullhorn",
			"fa fa-bell" => "bell",
			"fa fa-certificate" => "certificate",
			"fa fa-hand-o-right" => "Hand Outlined Right",
			"fa fa-hand-o-left" => "Hand Outlined Left",
			"fa fa-hand-o-up" => "Hand Outlined Up",
			"fa fa-hand-o-down" => "Hand Outlined Down",
			"fa fa-arrow-circle-left" => "Arrow Circle Left",
			"fa fa-arrow-circle-right" => "Arrow Circle Right",
			"fa fa-arrow-circle-up" => "Arrow Circle Up",
			"fa fa-arrow-circle-down" => "Arrow Circle Down",
			"fa fa-globe" => "Globe",
			"fa fa-wrench" => "Wrench",
			"fa fa-tasks" => "Tasks",
			"fa fa-filter" => "Filter",
			"fa fa-briefcase" => "Briefcase",
			"fa fa-arrows-alt" => "Arrows Alt",
			"fa fa-users" => "Users",
			"fa fa-link" => "Link",
			"fa fa-cloud" => "Cloud",
			"fa fa-flask" => "Flask",
			"fa fa-scissors" => "Scissors",
			"fa fa-files-o" => "Files Outlined",
			"fa fa-paperclip" => "Paperclip",
			"fa fa-floppy-o" => "Floppy Outlined",
			"fa fa-square" => "Square",
			"fa fa-bars" => "Bars",
			"fa fa-list-ul" => "list-ul",
			"fa fa-list-ol" => "list-ol",
			"fa fa-strikethrough" => "Strikethrough",
			"fa fa-underline" => "Underline",
			"fa fa-table" => "table",
			"fa fa-magic" => "magic",
			"fa fa-truck" => "truck",
			"fa fa-pinterest" => "Pinterest",
			"fa fa-pinterest-square" => "Pinterest Square",
			"fa fa-google-plus-square" => "Google Plus Square",
			"fa fa-google-plus" => "Google Plus",
			"fa fa-money" => "Money",
			"fa fa-caret-down" => "Caret Down",
			"fa fa-caret-up" => "Caret Up",
			"fa fa-caret-left" => "Caret Left",
			"fa fa-caret-right" => "Caret Right",
			"fa fa-columns" => "Columns",
			"fa fa-sort" => "Sort",
			"fa fa-sort-desc" => "Sort Descending",
			"fa fa-sort-asc" => "Sort Ascending",
			"fa fa-envelope" => "Envelope",
			"fa fa-linkedin" => "LinkedIn",
			"fa fa-undo" => "Undo",
			"fa fa-gavel" => "Gavel",
			"fa fa-tachometer" => "Tachometer",
			"fa fa-comment-o" => "comment-o",
			"fa fa-comments-o" => "comments-o",
			"fa fa-bolt" => "Lightning Bolt",
			"fa fa-sitemap" => "Sitemap",
			"fa fa-umbrella" => "Umbrella",
			"fa fa-clipboard" => "Clipboard",
			"fa fa-lightbulb-o" => "Lightbulb Outlined",
			"fa fa-exchange" => "Exchange",
			"fa fa-cloud-download" => "Cloud Download",
			"fa fa-cloud-upload" => "Cloud Upload",
			"fa fa-user-md" => "user-md",
			"fa fa-stethoscope" => "Stethoscope",
			"fa fa-suitcase" => "Suitcase",
			"fa fa-bell-o" => "Bell Outlined",
			"fa fa-coffee" => "Coffee",
			"fa fa-cutlery" => "Cutlery",
			"fa fa-file-text-o" => "File Text Outlined",
			"fa fa-building-o" => "Building Outlined",
			"fa fa-hospital-o" => "hospital Outlined",
			"fa fa-ambulance" => "ambulance",
			"fa fa-medkit" => "medkit",
			"fa fa-fighter-jet" => "fighter-jet",
			"fa fa-beer" => "beer",
			"fa fa-h-square" => "H Square",
			"fa fa-plus-square" => "Plus Square",
			"fa fa-angle-double-left" => "Angle Double Left",
			"fa fa-angle-double-right" => "Angle Double Right",
			"fa fa-angle-double-up" => "Angle Double Up",
			"fa fa-angle-double-down" => "Angle Double Down",
			"fa fa-angle-left" => "angle-left",
			"fa fa-angle-right" => "angle-right",
			"fa fa-angle-up" => "angle-up",
			"fa fa-angle-down" => "angle-down",
			"fa fa-desktop" => "Desktop",
			"fa fa-laptop" => "Laptop",
			"fa fa-tablet" => "tablet",
			"fa fa-mobile" => "Mobile Phone",
			"fa fa-circle-o" => "Circle Outlined",
			"fa fa-quote-left" => "quote-left",
			"fa fa-quote-right" => "quote-right",
			"fa fa-spinner" => "Spinner",
			"fa fa-circle" => "Circle",
			"fa fa-reply" => "Reply",
			"fa fa-github-alt" => "GitHub Alt",
			"fa fa-folder-o" => "Folder Outlined",
			"fa fa-folder-open-o" => "Folder Open Outlined",
			"fa fa-smile-o" => "Smile Outlined",
			"fa fa-frown-o" => "Frown Outlined",
			"fa fa-meh-o" => "Meh Outlined",
			"fa fa-gamepad" => "Gamepad",
			"fa fa-keyboard-o" => "Keyboard Outlined",
			"fa fa-flag-o" => "Flag Outlined",
			"fa fa-flag-checkered" => "flag-checkered",
			"fa fa-terminal" => "Terminal",
			"fa fa-code" => "Code",
			"fa fa-reply-all" => "reply-all",
			"fa fa-star-half-o" => "Star Half Outlined",
			"fa fa-location-arrow" => "location-arrow",
			"fa fa-crop" => "crop",
			"fa fa-code-fork" => "code-fork",
			"fa fa-chain-broken" => "Chain Broken",
			"fa fa-question" => "Question",
			"fa fa-info" => "Info",
			"fa fa-exclamation" => "exclamation",
			"fa fa-superscript" => "superscript",
			"fa fa-subscript" => "subscript",
			"fa fa-eraser" => "eraser",
			"fa fa-puzzle-piece" => "Puzzle Piece",
			"fa fa-microphone" => "microphone",
			"fa fa-microphone-slash" => "Microphone Slash",
			"fa fa-shield" => "shield",
			"fa fa-calendar-o" => "calendar-o",
			"fa fa-fire-extinguisher" => "fire-extinguisher",
			"fa fa-rocket" => "rocket",
			"fa fa-maxcdn" => "MaxCDN",
			"fa fa-chevron-circle-left" => "Chevron Circle Left",
			"fa fa-chevron-circle-right" => "Chevron Circle Right",
			"fa fa-chevron-circle-up" => "Chevron Circle Up",
			"fa fa-chevron-circle-down" => "Chevron Circle Down",
			"fa fa-html5" => "HTML 5 Logo",
			"fa fa-css3" => "CSS 3 Logo",
			"fa fa-anchor" => "Anchor",
			"fa fa-unlock-alt" => "Unlock Alt",
			"fa fa-bullseye" => "Bullseye",
			"fa fa-ellipsis-h" => "Ellipsis Horizontal",
			"fa fa-ellipsis-v" => "Ellipsis Vertical",
			"fa fa-rss-square" => "RSS Square",
			"fa fa-play-circle" => "Play Circle",
			"fa fa-ticket" => "Ticket",
			"fa fa-minus-square" => "Minus Square",
			"fa fa-minus-square-o" => "Minus Square Outlined",
			"fa fa-level-up" => "Level Up",
			"fa fa-level-down" => "Level Down",
			"fa fa-check-square" => "Check Square",
			"fa fa-pencil-square" => "Pencil Square",
			"fa fa-external-link-square" => "External Link Square",
			"fa fa-share-square" => "Share Square",
			"fa fa-compass" => "Compass",
			"fa fa-caret-square-o-down" => "Caret Square Outlined Down",
			"fa fa-caret-square-o-up" => "Caret Square Outlined Up",
			"fa fa-caret-square-o-right" => "Caret Square Outlined Right",
			"fa fa-eur" => "Euro (EUR)",
			"fa fa-gbp" => "GBP",
			"fa fa-usd" => "US Dollar",
			"fa fa-inr" => "Indian Rupee (INR)",
			"fa fa-jpy" => "Japanese Yen (JPY)",
			"fa fa-rub" => "Russian Ruble (RUB)",
			"fa fa-krw" => "Korean Won (KRW)",
			"fa fa-btc" => "Bitcoin (BTC)",
			"fa fa-file" => "File",
			"fa fa-file-text" => "File Text",
			"fa fa-sort-alpha-asc" => "Sort Alpha Ascending",
			"fa fa-sort-alpha-desc" => "Sort Alpha Descending",
			"fa fa-sort-amount-asc" => "Sort Amount Ascending",
			"fa fa-sort-amount-desc" => "Sort Amount Descending",
			"fa fa-sort-numeric-asc" => "Sort Numeric Ascending",
			"fa fa-sort-numeric-desc" => "Sort Numeric Descending",
			"fa fa-thumbs-up" => "thumbs-up",
			"fa fa-thumbs-down" => "thumbs-down",
			"fa fa-youtube-square" => "YouTube Square",
			"fa fa-youtube" => "YouTube",
			"fa fa-xing" => "Xing",
			"fa fa-xing-square" => "Xing Square",
			"fa fa-youtube-play" => "YouTube Play",
			"fa fa-dropbox" => "Dropbox",
			"fa fa-stack-overflow" => "Stack Overflow",
			"fa fa-instagram" => "Instagram",
			"fa fa-flickr" => "Flickr",
			"fa fa-adn" => "App.net",
			"fa fa-bitbucket" => "Bitbucket",
			"fa fa-bitbucket-square" => "Bitbucket Square",
			"fa fa-tumblr" => "Tumblr",
			"fa fa-tumblr-square" => "Tumblr Square",
			"fa fa-long-arrow-down" => "Long Arrow Down",
			"fa fa-long-arrow-up" => "Long Arrow Up",
			"fa fa-long-arrow-left" => "Long Arrow Left",
			"fa fa-long-arrow-right" => "Long Arrow Right",
			"fa fa-apple" => "Apple",
			"fa fa-windows" => "Windows",
			"fa fa-android" => "Android",
			"fa fa-linux" => "Linux",
			"fa fa-dribbble" => "Dribbble",
			"fa fa-skype" => "Skype",
			"fa fa-foursquare" => "Foursquare",
			"fa fa-trello" => "Trello",
			"fa fa-female" => "Female",
			"fa fa-male" => "Male",
			"fa fa-gratipay" => "Gratipay (Gittip)",
			"fa fa-sun-o" => "Sun Outlined",
			"fa fa-moon-o" => "Moon Outlined",
			"fa fa-archive" => "Archive",
			"fa fa-bug" => "Bug",
			"fa fa-vk" => "VK",
			"fa fa-weibo" => "Weibo",
			"fa fa-renren" => "Renren",
			"fa fa-pagelines" => "Pagelines",
			"fa fa-stack-exchange" => "Stack Exchange",
			"fa fa-arrow-circle-o-right" => "Arrow Circle Outlined Right",
			"fa fa-arrow-circle-o-left" => "Arrow Circle Outlined Left",
			"fa fa-caret-square-o-left" => "Caret Square Outlined Left",
			"fa fa-dot-circle-o" => "Dot Circle Outlined",
			"fa fa-wheelchair" => "Wheelchair",
			"fa fa-vimeo-square" => "Vimeo Square",
			"fa fa-try" => "Turkish Lira (TRY)",
			"fa fa-plus-square-o" => "Plus Square Outlined",
			"fa fa-space-shuttle" => "Space Shuttle",
			"fa fa-slack" => "Slack Logo",
			"fa fa-envelope-square" => "Envelope Square",
			"fa fa-wordpress" => "WordPress Logo",
			"fa fa-openid" => "OpenID",
			"fa fa-university" => "University",
			"fa fa-graduation-cap" => "Graduation Cap",
			"fa fa-yahoo" => "Yahoo Logo",
			"fa fa-google" => "Google Logo",
			"fa fa-reddit" => "reddit Logo",
			"fa fa-reddit-square" => "reddit Square",
			"fa fa-stumbleupon-circle" => "StumbleUpon Circle",
			"fa fa-stumbleupon" => "StumbleUpon Logo",
			"fa fa-delicious" => "Delicious Logo",
			"fa fa-digg" => "Digg Logo",
			"fa fa-pied-piper" => "Pied Piper Logo",
			"fa fa-pied-piper-alt" => "Pied Piper Alternate Logo",
			"fa fa-drupal" => "Drupal Logo",
			"fa fa-joomla" => "Joomla Logo",
			"fa fa-language" => "Language",
			"fa fa-fax" => "Fax",
			"fa fa-building" => "Building",
			"fa fa-child" => "Child",
			"fa fa-paw" => "Paw",
			"fa fa-spoon" => "spoon",
			"fa fa-cube" => "Cube",
			"fa fa-cubes" => "Cubes",
			"fa fa-behance" => "Behance",
			"fa fa-behance-square" => "Behance Square",
			"fa fa-steam" => "Steam",
			"fa fa-steam-square" => "Steam Square",
			"fa fa-recycle" => "Recycle",
			"fa fa-car" => "Car",
			"fa fa-taxi" => "Taxi",
			"fa fa-tree" => "Tree",
			"fa fa-spotify" => "Spotify",
			"fa fa-deviantart" => "deviantART",
			"fa fa-soundcloud" => "SoundCloud",
			"fa fa-database" => "Database",
			"fa fa-file-pdf-o" => "PDF File Outlined",
			"fa fa-file-word-o" => "Word File Outlined",
			"fa fa-file-excel-o" => "Excel File Outlined",
			"fa fa-file-powerpoint-o" => "Powerpoint File Outlined",
			"fa fa-file-image-o" => "Image File Outlined",
			"fa fa-file-archive-o" => "Archive File Outlined",
			"fa fa-file-audio-o" => "Audio File Outlined",
			"fa fa-file-video-o" => "Video File Outlined",
			"fa fa-file-code-o" => "Code File Outlined",
			"fa fa-vine" => "Vine",
			"fa fa-codepen" => "Codepen",
			"fa fa-jsfiddle" => "jsFiddle",
			"fa fa-life-ring" => "Life Ring",
			"fa fa-circle-o-notch" => "Circle Outlined Notched",
			"fa fa-rebel" => "Rebel Alliance",
			"fa fa-empire" => "Galactic Empire",
			"fa fa-git-square" => "Git Square",
			"fa fa-git" => "Git",
			"fa fa-hacker-news" => "Hacker News",
			"fa fa-tencent-weibo" => "Tencent Weibo",
			"fa fa-qq" => "QQ",
			"fa fa-weixin" => "Weixin (WeChat)",
			"fa fa-paper-plane" => "Paper Plane",
			"fa fa-paper-plane-o" => "Paper Plane Outlined",
			"fa fa-history" => "History",
			"fa fa-circle-thin" => "Circle Outlined Thin",
			"fa fa-header" => "header",
			"fa fa-paragraph" => "paragraph",
			"fa fa-sliders" => "Sliders",
			"fa fa-share-alt" => "Share Alt",
			"fa fa-share-alt-square" => "Share Alt Square",
			"fa fa-bomb" => "Bomb",
			"fa fa-futbol-o" => "Futbol Outlined",
			"fa fa-tty" => "TTY",
			"fa fa-binoculars" => "Binoculars",
			"fa fa-plug" => "Plug",
			"fa fa-slideshare" => "Slideshare",
			"fa fa-twitch" => "Twitch",
			"fa fa-yelp" => "Yelp",
			"fa fa-newspaper-o" => "Newspaper Outlined",
			"fa fa-wifi" => "WiFi",
			"fa fa-calculator" => "Calculator",
			"fa fa-paypal" => "Paypal",
			"fa fa-google-wallet" => "Google Wallet",
			"fa fa-cc-visa" => "Visa Credit Card",
			"fa fa-cc-mastercard" => "MasterCard Credit Card",
			"fa fa-cc-discover" => "Discover Credit Card",
			"fa fa-cc-amex" => "American Express Credit Card",
			"fa fa-cc-paypal" => "Paypal Credit Card",
			"fa fa-cc-stripe" => "Stripe Credit Card",
			"fa fa-bell-slash" => "Bell Slash",
			"fa fa-bell-slash-o" => "Bell Slash Outlined",
			"fa fa-trash" => "Trash",
			"fa fa-copyright" => "Copyright",
			"fa fa-at" => "At",
			"fa fa-eyedropper" => "Eyedropper",
			"fa fa-paint-brush" => "Paint Brush",
			"fa fa-birthday-cake" => "Birthday Cake",
			"fa fa-area-chart" => "Area Chart",
			"fa fa-pie-chart" => "Pie Chart",
			"fa fa-line-chart" => "Line Chart",
			"fa fa-lastfm" => "last.fm",
			"fa fa-lastfm-square" => "last.fm Square",
			"fa fa-toggle-off" => "Toggle Off",
			"fa fa-toggle-on" => "Toggle On",
			"fa fa-bicycle" => "Bicycle",
			"fa fa-bus" => "Bus",
			"fa fa-ioxhost" => "ioxhost",
			"fa fa-angellist" => "AngelList",
			"fa fa-cc" => "Closed Captions",
			"fa fa-ils" => "Shekel (ILS)",
			"fa fa-meanpath" => "meanpath",
			"fa fa-buysellads" => "BuySellAds",
			"fa fa-connectdevelop" => "Connect Develop",
			"fa fa-dashcube" => "DashCube",
			"fa fa-forumbee" => "Forumbee",
			"fa fa-leanpub" => "Leanpub",
			"fa fa-sellsy" => "Sellsy",
			"fa fa-shirtsinbulk" => "Shirts in Bulk",
			"fa fa-simplybuilt" => "SimplyBuilt",
			"fa fa-skyatlas" => "skyatlas",
			"fa fa-cart-plus" => "Add to Shopping Cart",
			"fa fa-cart-arrow-down" => "Shopping Cart Arrow Down",
			"fa fa-diamond" => "Diamond",
			"fa fa-ship" => "Ship",
			"fa fa-user-secret" => "User Secret",
			"fa fa-motorcycle" => "Motorcycle",
			"fa fa-street-view" => "Street View",
			"fa fa-heartbeat" => "Heartbeat",
			"fa fa-venus" => "Venus",
			"fa fa-mars" => "Mars",
			"fa fa-mercury" => "Mercury",
			"fa fa-transgender" => "Transgender",
			"fa fa-transgender-alt" => "Transgender Alt",
			"fa fa-venus-double" => "Venus Double",
			"fa fa-mars-double" => "Mars Double",
			"fa fa-venus-mars" => "Venus Mars",
			"fa fa-mars-stroke" => "Mars Stroke",
			"fa fa-mars-stroke-v" => "Mars Stroke Vertical",
			"fa fa-mars-stroke-h" => "Mars Stroke Horizontal",
			"fa fa-neuter" => "Neuter",
			"fa fa-genderless" => "Genderless",
			"fa fa-facebook-official" => "Facebook Official",
			"fa fa-pinterest-p" => "Pinterest P",
			"fa fa-whatsapp" => "What's App",
			"fa fa-server" => "Server",
			"fa fa-user-plus" => "Add User",
			"fa fa-user-times" => "Remove User",
			"fa fa-bed" => "Bed",
			"fa fa-viacoin" => "Viacoin",
			"fa fa-train" => "Train",
			"fa fa-subway" => "Subway",
			"fa fa-medium" => "Medium",
			"fa fa-y-combinator" => "Y Combinator",
			"fa fa-optin-monster" => "Optin Monster",
			"fa fa-opencart" => "OpenCart",
			"fa fa-expeditedssl" => "ExpeditedSSL",
			"fa fa-battery-full" => "Battery Full",
			"fa fa-battery-three-quarters" => "Battery 3/4 Full",
			"fa fa-battery-half" => "Battery 1/2 Full",
			"fa fa-battery-quarter" => "Battery 1/4 Full",
			"fa fa-battery-empty" => "Battery Empty",
			"fa fa-mouse-pointer" => "Mouse Pointer",
			"fa fa-i-cursor" => "I Beam Cursor",
			"fa fa-object-group" => "Object Group",
			"fa fa-object-ungroup" => "Object Ungroup",
			"fa fa-sticky-note" => "Sticky Note",
			"fa fa-sticky-note-o" => "Sticky Note Outlined",
			"fa fa-cc-jcb" => "JCB Credit Card",
			"fa fa-cc-diners-club" => "Diner's Club Credit Card",
			"fa fa-clone" => "Clone",
			"fa fa-balance-scale" => "Balance Scale",
			"fa fa-hourglass-o" => "Hourglass Outlined",
			"fa fa-hourglass-start" => "Hourglass Start",
			"fa fa-hourglass-half" => "Hourglass Half",
			"fa fa-hourglass-end" => "Hourglass End",
			"fa fa-hourglass" => "Hourglass",
			"fa fa-hand-rock-o" => "Rock (Hand)",
			"fa fa-hand-paper-o" => "Paper (Hand)",
			"fa fa-hand-scissors-o" => "Scissors (Hand)",
			"fa fa-hand-lizard-o" => "Lizard (Hand)",
			"fa fa-hand-spock-o" => "Spock (Hand)",
			"fa fa-hand-pointer-o" => "Hand Pointer",
			"fa fa-hand-peace-o" => "Hand Peace",
			"fa fa-trademark" => "Trademark",
			"fa fa-registered" => "Registered Trademark",
			"fa fa-creative-commons" => "Creative Commons",
			"fa fa-gg" => "GG Currency",
			"fa fa-gg-circle" => "GG Currency Circle",
			"fa fa-tripadvisor" => "TripAdvisor",
			"fa fa-odnoklassniki" => "Odnoklassniki",
			"fa fa-odnoklassniki-square" => "Odnoklassniki Square",
			"fa fa-get-pocket" => "Get Pocket",
			"fa fa-wikipedia-w" => "Wikipedia W",
			"fa fa-safari" => "Safari",
			"fa fa-chrome" => "Chrome",
			"fa fa-firefox" => "Firefox",
			"fa fa-opera" => "Opera",
			"fa fa-internet-explorer" => "Internet-explorer",
			"fa fa-television" => "Television",
			"fa fa-contao" => "Contao",
			"fa fa-500px" => "500px",
			"fa fa-amazon" => "Amazon",
			"fa fa-calendar-plus-o" => "Calendar Plus Outlined",
			"fa fa-calendar-minus-o" => "Calendar Minus Outlined",
			"fa fa-calendar-times-o" => "Calendar Times Outlined",
			"fa fa-calendar-check-o" => "Calendar Check Outlined",
			"fa fa-industry" => "Industry",
			"fa fa-map-pin" => "Map Pin",
			"fa fa-map-signs" => "Map Signs",
			"fa fa-map-o" => "Map Outline",
			"fa fa-map" => "Map",
			"fa fa-commenting" => "Commenting",
			"fa fa-commenting-o" => "Commenting Outlined",
			"fa fa-houzz" => "Houzz",
			"fa fa-vimeo" => "Vimeo",
			"fa fa-black-tie" => "Font Awesome Black Tie",
			"fa fa-fonticons" => "Fonticons",
			"fa fa-reddit-alien" => "reddit Alien",
			"fa fa-edge" => "Edge Browser",
			"fa fa-credit-card-alt" => "Credit Card",
			"fa fa-codiepie" => "Codie Pie",
			"fa fa-modx" => "MODX",
			"fa fa-fort-awesome" => "Fort Awesome",
			"fa fa-usb" => "USB",
			"fa fa-product-hunt" => "Product Hunt",
			"fa fa-mixcloud" => "Mixcloud",
			"fa fa-scribd" => "Scribd",
			"fa fa-pause-circle" => "Pause Circle",
			"fa fa-pause-circle-o" => "Pause Circle Outlined",
			"fa fa-stop-circle" => "Stop Circle",
			"fa fa-stop-circle-o" => "Stop Circle Outlined",
			"fa fa-shopping-bag" => "Shopping Bag",
			"fa fa-shopping-basket" => "Shopping Basket",
			"fa fa-hashtag" => "Hashtag",
			"fa fa-bluetooth" => "Bluetooth",
			"fa fa-bluetooth-b" => "Bluetooth",
			"fa fa-percent" => "Percent",
		);
		
		$icon_font = apply_filters( 'ctf_icon_class_array', $icon_font );

		return $icon_font;
	}
	
	/**
	 * Get all fields name
	 */
	public static function get_all_fields_name(){
		$all_fields = array(
			'text',
			'text_multi',
			'textarea',
			'email',
			'number',
			'dimension',
			'range',
			'password',
			'url',
			'select',
			'radio',
			'radio_image',
			'radio_button',
			'checkbox',
			'checkbox_image',
			'checkbox_button',
			'color',
			'color_rgba',
			'google_font',
			'font_style',
			'text_align',
			'icon',
			'image',
			'editor',
			'image_multi',
			'readonly'
		);
		
		/**
		 * Filter the fields name array for adding new field from your theme or plugin
		 */
		apply_filters('ctf_fields_name', $all_fields);
		
		return $all_fields;
	}
	
	
	public static function is_js_tmpl_printed(){
		return self::$is_fields_printed_at_admin_footer;
	}

	public static function set_js_tmpl_printed( $boolval ){
		self::$is_fields_printed_at_admin_footer = $boolval;
	}
}

endif; // End if class_exists check